[localthings]
# List of networks to scan for devices. If empty, all networks will be scanned. Networks must be specified in CIDR notation
discovery_networks = 

# Poll interval in minutes for the cron job that updates the devices' information. Allowed values are: 10s, 20s, 30s, 1, 2, 3, 4, 5, 10, 15, 20, 30, 45, 60, 120, 240, 360, 720 and 1440.
poll_interval = 2

