[localthings]
# List of networks to scan for devices. If empty, all networks will be scanned. Networks must be specified in CIDR notation
discovery_networks = 

# Poll intervals selected independently from the last known connection state.
# Allowed values are: 10s, 20s, 30s, 1, 2, 3, 4, 5, 10, 15, 20, 30, 45, 60, 120, 240, 360, 720 and 1440.
poll_interval_online = 30s
poll_interval_offline = 5
